=== ArrayIterator/whmcs-pentagonal-addons/schema/plugin.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://hub.pentagonal.org/schemas/plugin.json",
    "type": "object",
    "title": "Schema for plugin",
    "description": "The schema for plugin",
    "version": "1.0.0",
    "required": [
        "name",
        "namespace"
    ],
    "properties": {
        "$schema": {
            "description": "The schema uri of the plugin",
            "type": "string"
        },
        "$id": {
            "description": "The id of the plugin",
            "type": "string",
            "format": "uri"
        },
        "name": {
            "description": "The name of the plugin",
            "type": "string"
        },
        "version": {
            "description": "The version of the plugin",
            "type": "string"
        },
        "url": {
            "description": "The url of the plugin",
            "type": "string",
            "format": "uri"
        },
        "author": {
            "description": "The author of the plugin",
            "type": "string"
        },
        "author_url": {
            "description": "The author url of the plugin",
            "type": "string",
            "format": "uri"
        },
        "license": {
            "description": "The license of the plugin",
            "type": "string"
        },
        "license_url": {
            "description": "The license url of the plugin",
            "type": "string",
            "format": "uri"
        },
        "enable_admin_page": {
            "description": "Enable Page on addon plugin",
            "default": false,
            "type": "boolean"
        },
        "namespace": {
            "description": "The namespace of the plugin class",
            "pattern": "^[a-zA-Z_\\x7f-\\xff][a-zA-Z0-9_\\x7f-\\xff]*(\\\\[a-zA-Z_\\x7f-\\xff][a-zA-Z0-9_\\x7f-\\xff]*)*$",
            "type": "string"
        }
    }
}

=== ArrayIterator/whmcs-pentagonal-addons/plugins/debug-bar/plugin.json
{
    "$schema": "../../schema/plugin.json",
    "name": "File Manager",
    "version": "https://www.pentagonal.org/",
    "url": "https://www.pentagonal.org/",
    "author": "Pentagonal",
    "author_url": "https://www.pentagonal.org/",
    "license": "proprietary",
    "license_url": "https://www.pentagonal.org/",
    "namespace": "Pentagonal/Neon/WHMCS/Plugins/DebugBar",
    "enable_admin_page": true
}
